### ISSUE TITLE
Science-Parser errors

### ISSUE THREAD

**Issue by stevaras2** [guyfe/LongSumm#1]
I tried to parse the PDF files of the abstractive dataset using the science-parse server using the command: _curl -v -H "Content-type: application/pdf" --data-binary @paper.pdf "http://scienceparse.allenai.org/v1"_ but I got refuse to connect error. 
Also, I downloaded the science-parse jar file from the following link _https://github.com/allenai/science-parse/releases/download/v1.3.2/science-parse-cli-assembly-1.3.2.jar_, and it parses only 175 out of 516 PDF files. For the remaining files I got the following error:
_Parsing filename.pdf failed with java.io.IOException: Error: End-of-File, expected line_.
Does anyone find a way to fix these problems?

**Comment by guyfe** [comment]
@stevaras2 , thanks for reaching out. We will update the path to scienceparse. 
With respect to the parsing errors, did you check that your domain has subscription to the publisher websites ? Maybe try to access some of these papers from your browser ?

**Comment by stevaras2** [comment]
@guyfe ,  I tried to parse the PDF files of the abstractive dataset that you provide via the downloader.py script.

**Comment by guyfe** [comment]
I understand but if you don't have access to the publisher website you will not be able to download the pdf - the script doesn't bypass the subscription, as we wrote in the readme:

> Notice - some of the papers may require a subscription (e.g., ACM). If you do not have the permission the script won't be able to download the paper.

**Comment by stevaras2** [comment]
I have already downloaded the PDF files

**Comment by Saichethan** [comment]
Hello @stevaras2 I'm experiencing similar probem but unlike you when I'm running sbt cli/assembly I'm getting core / Compile / compileIncremental) java.lang.ExceptionInInitializerError please let me know how you solved this

And when I downloaded the science-parse jar file from the following link https://github.com/allenai/science-parse/releases/download/v1.3.2/science-parse-cli-assembly-1.3.2.jar,  I'm getting time out error

**Comment by stevaras2** [comment]
> Hello @stevaras2 I'm experiencing similar probem but unlike you when I'm running sbt cli/assembly I'm getting core / Compile / compileIncremental) java.lang.ExceptionInInitializerError please let me know how you solved this
> 
> And when I downloaded the science-parse jar file from the following link https://github.com/allenai/science-parse/releases/download/v1.3.2/science-parse-cli-assembly-1.3.2.jar, I'm getting time out error
