### ISSUE TITLE
issues with downloader.py

### ISSUE THREAD

**Issue by Saichethan** [guyfe/LongSumm#2]
There is a typo it's --num_processes but mentioned --num_processors in README.md

And in Cluster 0_100 when opening a PDF it showed the following error 
Unable to open document “file:///home/reddy/LongSumm/abstractive_summaries/PDF/1077676.pdf”.

**Comment by guyfe** [comment]
Thanks @Saichethan , fixed the typo :

> There is a typo it's --num_processes but mentioned --num_processors in README.md

Are you able to download the paper manually (without the script) ?  
> And in Cluster 0_100 when opening a PDF it showed the following error
Unable to open document “file:///home/reddy/LongSumm/abstractive_summaries/PDF/1077676.pdf

As we wrote in the  README,  some of the papers may require a subscription (e.g., ACM). If you do not have the permission the script won't be able to download the paper.

**Comment by Saichethan** [comment]
Ok that explains. @guyfe 

One more thing when running science parser "sbt cli/assembly"
I'm getting (core / Compile / compileIncremental) java.lang.ExceptionInInitializerError)
![Screenshot from 2020-04-26 16-26-37](https://user-images.githubusercontent.com/34788026/80305548-f7e7b800-87da-11ea-92d4-f9989b32cae6.png)
