### ISSUE TITLE
Link to reference papers not available for extractive summaries

### ISSUE THREAD

**Issue by ravi03071991** [guyfe/LongSumm#3]
Hi,

In the README file, you mentioned in the following way:

> The format of each summary file is as follows:
> 
> 1. Each line contains sentence index (in the original paper), sentence score (i.e. duration), then the sentence itself. The fields are tab-separated.
> 2. The order of the sentences is according to their order in the paper.
> 3. Link to the reference paper.

but the link to reference paper is not available in the summary file. Can you please help me to get the PDF paper or link to the PDF paper of the specific summary file?

Regards,
D. Ravi Theja.

**Comment by guyfe** [comment]
Hi @ravi03071991 , thanks for your interest. We uploaded the following file with a mapping between a paper title to its path in the publisher website :
[https://github.com/guyfe/LongSumm/blob/master/extractive_summaries/talksumm_papers_titles_url.txt](https://github.com/guyfe/LongSumm/blob/master/extractive_summaries/talksumm_papers_titles_url.txt)

**Comment by ravi03071991** [comment]
Thank you @guyfe.
