### ISSUE TITLE
Error using downloader.py program

### ISSUE THREAD

**Issue by sainikmahata** [guyfe/LongSumm#5]
I cloned the whole LongSumm folder. I then changed the directory to scripts. Also, created another folder named "papers" that will act as my output directory. But, when I run the program "downloader.py", I get the following error.
![Screenshot 2021-02-03 161328](https://user-images.githubusercontent.com/16027591/106736154-1963b300-663b-11eb-990b-7f275b4a1c36.png)
KIndly help me regarding this.

**Comment by guyfe** [comment]
Do you get this error only for a specific paper or always ? 
As we wrote in the instructions :
```Notice - some of the papers may require a subscription (e.g., ACM). If you do not have the permission the script won't be able to download the paper.```
Could you check that?

**Comment by sainikmahata** [comment]
Yes Sir, it was not working for certain papers. Thanks for the
clarification. I finally managed to download all the files. You can mark
the issue as closed.

**Comment by guyfe** [comment]
Thanks for the update and good luck with the task !

**Comment by arnold-em** [comment]
Hello sir, can you put the complete dataset on github, because some certain papers i can not download,the dataset not complete.... thank u sir
